global:
   scrape_interval: 10s # By default, scrape targets every 15 seconds.
   evaluation_interval: 10s
   external_labels:
      monitor: "CI/CD Portfolio"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
   - job_name: "backend"
     static_configs:
        - targets: ["portfolio-backend:5000"]

   - job_name: "prometheus"
     static_configs:
        - targets: ["prometheus:9090"]

   - job_name: "grafana"
     static_configs:
        - targets: ["grafana:7070"]

   - job_name: "cadvisor"
     static_configs:
        - targets: ["cadvisor:8080"]

   - job_name: "alert-manager"
     static_configs:
        - targets: ["alertmanager:9093"]

alerting:
   alertmanagers:
      - static_configs:
           - targets: ["alertmanager:9093"]

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
   - /etc/prometheus/alert_rules.yml
